//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasERP.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AtlasERP.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        public static string DemoMode {
            get {
                return ResourceManager.GetString("DemoMode", resourceCulture);
            }
        }
        
        public static string DemoModeInfo {
            get {
                return ResourceManager.GetString("DemoModeInfo", resourceCulture);
            }
        }
        
        public static string DemoAdminInfo {
            get {
                return ResourceManager.GetString("DemoAdminInfo", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        public static string OrganizationManagement {
            get {
                return ResourceManager.GetString("OrganizationManagement", resourceCulture);
            }
        }
        
        public static string ModuleManagement {
            get {
                return ResourceManager.GetString("ModuleManagement", resourceCulture);
            }
        }
        
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        public static string DashboardDescription {
            get {
                return ResourceManager.GetString("DashboardDescription", resourceCulture);
            }
        }
        
        public static string SalesOverview {
            get {
                return ResourceManager.GetString("SalesOverview", resourceCulture);
            }
        }
        
        public static string InventoryStatus {
            get {
                return ResourceManager.GetString("InventoryStatus", resourceCulture);
            }
        }
        
        public static string ActiveEmployees {
            get {
                return ResourceManager.GetString("ActiveEmployees", resourceCulture);
            }
        }
        
        public static string PendingTransactions {
            get {
                return ResourceManager.GetString("PendingTransactions", resourceCulture);
            }
        }
        
        public static string FromLastMonth {
            get {
                return ResourceManager.GetString("FromLastMonth", resourceCulture);
            }
        }
        
        public static string LowStockAlerts {
            get {
                return ResourceManager.GetString("LowStockAlerts", resourceCulture);
            }
        }
        
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        public static string NewThisMonth {
            get {
                return ResourceManager.GetString("NewThisMonth", resourceCulture);
            }
        }
        
        public static string RequiresApproval {
            get {
                return ResourceManager.GetString("RequiresApproval", resourceCulture);
            }
        }
        
        public static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        public static string ActiveModules {
            get {
                return ResourceManager.GetString("ActiveModules", resourceCulture);
            }
        }
        
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        public static string UserManagementTitle {
            get {
                return ResourceManager.GetString("UserManagementTitle", resourceCulture);
            }
        }
        
        public static string UserManagementDescription {
            get {
                return ResourceManager.GetString("UserManagementDescription", resourceCulture);
            }
        }
        
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string OrganizationManagementTitle {
            get {
                return ResourceManager.GetString("OrganizationManagementTitle", resourceCulture);
            }
        }
        
        public static string OrganizationManagementDescription {
            get {
                return ResourceManager.GetString("OrganizationManagementDescription", resourceCulture);
            }
        }
        
        public static string AddOrganization {
            get {
                return ResourceManager.GetString("AddOrganization", resourceCulture);
            }
        }
        
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string ModuleManagementTitle {
            get {
                return ResourceManager.GetString("ModuleManagementTitle", resourceCulture);
            }
        }
        
        public static string ModuleManagementDescription {
            get {
                return ResourceManager.GetString("ModuleManagementDescription", resourceCulture);
            }
        }
        
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string LanguageSelectionInfo {
            get {
                return ResourceManager.GetString("LanguageSelectionInfo", resourceCulture);
            }
        }
        
        public static string LanguageChangeInfo {
            get {
                return ResourceManager.GetString("LanguageChangeInfo", resourceCulture);
            }
        }
        
        public static string LanguageChangeDescription {
            get {
                return ResourceManager.GetString("LanguageChangeDescription", resourceCulture);
            }
        }
    }
}
